### ISSUE TITLE
Failed to invoke msdfgen.exe when dealing with some CJK font

### ISSUE THREAD

**Issue by ghost** [donmccurdy/msdf-bmfont-web#15]
Sometime character shapedesc may become too complex to pass as a command line argument.
Node on windows has a nasty limitation about length of line argument: 8191 bytes
A simple workaround would be passing shapedesc through stdin.

changes in index.js
  let command = `${binaryPath} ${fieldType} -format text -stdout -size ${width} ${height} -translate ${xOffset} ${yOffset} -pxrange ${distanceRange} -stdin`;
  //-defineshape "${shapeDesc}"`;
and
  proc.stdin.write(shapeDesc);
  proc.stdin.write('\n\n');
  proc.stdin.destroy();
Solves this.

**Comment by donmccurdy** [comment]
Thanks! Would you want to try a Pull Request fixing this? Note that this is running on https://vercel.com/ though, I don't think any Windows CLI limitations should be relevant here...

>  proc.stdin.destroy();

Is this safe if the function might be called again?

**Comment by ghost** [comment]
I'm sorry for creating a wrong issue. The problem comes from **msdf-bmfont-xml**. Your code runs smoothly.

Let me close this issue now.
