### ISSUE TITLE
Font not working on iOS when Web GL 2.0 enabled.

### ISSUE THREAD

**Issue by daCking15** [donmccurdy/msdf-bmfont-web#19]
Hello. I generated a font using this tool with the french alphabet. It works on all platforms except iOS Safari when Web GL 2.0 is enabled. When Web GL 2.0 is disabled, it works perfectly, but I need Web GL 2.0 enabled for other uses. Any help would be appreciated. Here are the errors:
![image](https://user-images.githubusercontent.com/15696956/145096479-dbcf2ee0-35ab-49d3-a710-19193fb4190b.png)
![image](https://user-images.githubusercontent.com/15696956/145096501-603e0c2a-b199-460b-bc9e-74f9a90b09f4.png)
![image](https://user-images.githubusercontent.com/15696956/145096519-6ca17ee3-3335-435e-8610-e7f0f8380bf6.png)

**Comment by donmccurdy** [comment]
The SDF fonts created by this tool can be rendered by any API (WebGL, WebGL2, Vulkan, Metal, ...) so I think this comes down to whatever library you're using to load the font in three.js. If that's three-bmfont-text then the relevant issue might be https://github.com/Jam3/three-bmfont-text/issues/38.
