### ISSUE TITLE
Currently only single-page bitmap fonts are supported.

### ISSUE THREAD

**Issue by arpu** [donmccurdy/msdf-bmfont-web#9]
with this font 
https://fonts.google.com/specimen/Luckiest+Guy
and
Characters
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890‘?’“!”(%)[#]{@}/&\<-+÷×=>®©$€£¥¢:;,.*

if i load the font with aframe-master i get 
components:text:error Error: Currently only single-page bitmap fonts are supported.
looks like the texture size is to small to only use one texture image

**Comment by donmccurdy** [comment]
Yeah, the problem is that A-Frame doesn't support multi-page bitmap fonts: https://github.com/aframevr/aframe/issues/3355

I'll likely add some control over texture size (https://github.com/donmccurdy/msdf-bmfont-web/issues/5) so that it's easier to pack more text into a single texture, as well.

**Comment by arpu** [comment]
looks like the default 256x256 is really small? 
https://github.com/soimy/msdf-bmfont-xml/blob/master/cli.js#L21

**Comment by donmccurdy** [comment]
The ideal thing to do is to export exactly the characters you need for each experience, and keep the number and size of textures to an absolute minimum. But yeah, I do plan to expose some of those options in the UI eventually.
